### GET request with a header
// @no-redirect
GET https://httpbin.org/status/301
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
// @
GET https://www.ivonet.nl
Accept: text/html

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
